# Generated by Django 4.0.6 on 2022-07-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeMasonMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=256)),
                ('next_sync_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_identifier', models.CharField(max_length=256, null=True)),
                ('inspect_identifier', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('username', models.CharField(max_length=256)),
                ('pfp_url', models.TextField(null=True)),
                ('token', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeMasonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=256)),
                ('members_spotlight_count', models.PositiveIntegerField(default=50)),
                ('watching', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discord', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('opensea', models.CharField(blank=True, max_length=256, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_summarized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, to='freemasons.freemasonmember')),
            ],
        ),
        migrations.AddField(
            model_name='freemasonmember',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='freemasons.twitteruser'),
        ),
        migrations.AddField(
            model_name='freemasonmember',
            name='following',
            field=models.ManyToManyField(related_name='following', to='freemasons.twitteruser'),
        ),
        migrations.AddField(
            model_name='freemasonmember',
            name='twitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemasons.twitteruser'),
        ),
    ]
