# Generated by Django 4.0.6 on 2022-07-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeMasonMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('global_followings', models.PositiveIntegerField(default=0)),
                ('global_followers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeMasonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=256)),
                ('last_sync_at', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(to='freemasons.freemasonmember')),
            ],
        ),
        migrations.AddField(
            model_name='freemasonmember',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='freemasons.twitteruser'),
        ),
        migrations.AddField(
            model_name='freemasonmember',
            name='following',
            field=models.ManyToManyField(related_name='following', to='freemasons.twitteruser'),
        ),
        migrations.AddField(
            model_name='freemasonmember',
            name='twitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemasons.twitteruser'),
        ),
    ]
