# Generated by Django 4.0.6 on 2022-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0002_alter_freemasonproject_last_sync_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freemasonproject',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
