# Generated by Django 4.0.6 on 2022-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0003_alter_freemasonproject_last_sync_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='global_followers',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='global_followings',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='indentifier',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='pfp_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
