# Generated by Django 4.0.6 on 2022-07-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0004_remove_twitteruser_global_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='indentifier',
            new_name='identifier',
        ),
    ]
