# Generated by Django 4.0.6 on 2022-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0005_rename_indentifier_twitteruser_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='freemasonmember',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
