# Generated by Django 4.0.6 on 2022-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0007_rename_identifier_twitteruser_inspect_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freemasonproject',
            name='members_spotlight_count',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
