# Generated by Django 4.0.6 on 2022-07-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0008_freemasonproject_members_spotlight_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='freemasonproject',
            name='watching',
            field=models.BooleanField(default=False),
        ),
    ]
