# Generated by Django 4.0.6 on 2022-07-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0009_freemasonproject_watching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freemasonmember',
            old_name='last_sync_at',
            new_name='next_sync_at',
        ),
        migrations.RenameField(
            model_name='freemasonproject',
            old_name='last_sync_at',
            new_name='next_sync_at',
        ),
    ]
