# Generated by Django 4.0.6 on 2022-07-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0010_rename_last_sync_at_freemasonmember_next_sync_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freemasonproject',
            name='members',
            field=models.ManyToManyField(blank=True, to='freemasons.freemasonmember'),
        ),
        migrations.AlterField(
            model_name='freemasonproject',
            name='members_spotlight_count',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='freemasonproject',
            name='next_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
