# Generated by Django 4.0.6 on 2022-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemasons', '0011_alter_freemasonproject_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freemasonproject',
            name='last_summarized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
